# Generated by Django 3.2 on 2023-02-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
