# Generated by Django 4.0 on 2023-02-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teacher_expertise_teacher_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='expertise',
            field=models.CharField(default='', max_length=50, verbose_name='expertise'),
        ),
    ]
