# Generated by Django 4.0 on 2023-02-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='teacher_semester', to='teacher.Teacher'),
        ),
    ]
