# Generated by Django 4.0 on 2023-02-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_semester_teacher'),
        ('teacher', '0005_teacher_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='teacher_semester', to='school.Semester'),
        ),
    ]
