# Generated by Django 4.0 on 2023-02-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teacher_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher',
        ),
    ]
