# Generated by Django 4.0 on 2023-02-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_lesson_teachers'),
        ('teacher', '0007_remove_teacher_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='lessons',
        ),
        migrations.AddField(
            model_name='teacher',
            name='semestr',
            field=models.ManyToManyField(blank=True, related_name='teacher_semester', to='school.Semester'),
        ),
    ]
