# Generated by Django 3.2 on 2023-02-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_remove_teacher_lessons_teacher_semestr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='created_by',
        ),
    ]
