# Generated by Django 4.0 on 2023-01-18 19:04

import account.helpers
import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, help_text='Name contains only a-z and A-Z characters', max_length=150, validators=[django.core.validators.RegexValidator(message='Name contains only a-z and A-Z characters', regex="[a-zA-Z\\s']+")], verbose_name='first name')),
                ('last_name', models.CharField(blank=True, help_text='Name contains only a-z and A-Z characters', max_length=150, validators=[django.core.validators.RegexValidator(message='Name contains only a-z and A-Z characters', regex="[a-zA-Z\\s']+")], verbose_name='last name')),
                ('username', models.CharField(blank=True, help_text='Name contains only a-z and A-Z characters', max_length=150, validators=[django.core.validators.RegexValidator(message='Name contains only a-z and A-Z characters', regex="[a-zA-Z\\s']+")], verbose_name='username')),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the user is admin or not.', verbose_name='admin status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_superadmin', models.BooleanField(default=False, help_text='Designates whether the user is admin or not.', verbose_name='superadmin')),
                ('phone', models.CharField(blank=True, help_text='Phone number must be in this format:994xxxxxxxxx', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in this format:994xxxxxxxxx', regex='994\\s?\\d{2}[2-9]\\d{6}')], verbose_name='phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=account.helpers.get_profile_photo_upload_path)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birthdate')),
                ('type', models.CharField(choices=[('ADMIN', 'admin'), ('STUDENT', 'student'), ('TEACHER', 'teacher'), ('DRIVER', 'driver'), ('HOSTEL', 'hostel'), ('COACH', 'coache'), ('LIBRARIAN', 'librarian')], max_length=20, null=True, verbose_name='type')),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='ACTIVE', max_length=20, null=True, verbose_name='status')),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=20, null=True, verbose_name='gender')),
                ('payment_methods', multiselectfield.db.fields.MultiSelectField(max_length=20, null=True, verbose_name='payment_methods')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('password_updated_date', models.DateTimeField(default=datetime.datetime(2023, 1, 18, 19, 4, 17, 336692, tzinfo=utc), verbose_name='password updated date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
    ]
