# Generated by Django 4.0 on 2023-02-04 04:56

import ckeditor_uploader.fields
import config.helpers
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['first_name', 'last_name', 'username'], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AddField(
            model_name='account',
            name='adress',
            field=models.CharField(max_length=50, null=True, verbose_name='adress'),
        ),
        migrations.AddField(
            model_name='account',
            name='background_picture',
            field=models.ImageField(blank=True, null=True, upload_to='background-picture/'),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_admission',
            field=models.DateField(null=True, verbose_name='date of admission'),
        ),
        migrations.AddField(
            model_name='account',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='headline'),
        ),
        migrations.AddField(
            model_name='account',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='registration number'),
        ),
        migrations.AddField(
            model_name='account',
            name='show_headline_in_bio',
            field=models.BooleanField(default=False, verbose_name='I want to use this as my bio'),
        ),
        migrations.AddField(
            model_name='account',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Your Profile Summary'),
        ),
        migrations.AddField(
            model_name='account',
            name='website_links',
            field=models.URLField(default='', verbose_name='website links'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password_updated_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='password updated date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(null=True, upload_to=config.helpers.get_profile_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('DEAN', 'dean'), ('STUDENT', 'student'), ('TEACHER', 'teacher'), ('DRIVER', 'driver'), ('HOSTEL', 'hostel'), ('COACH', 'coache'), ('LIBRARIAN', 'librarian')], max_length=20, null=True, verbose_name='type'),
        ),
    ]
