# Generated by Django 4.0 on 2023-01-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password_updated_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='password updated date'),
        ),
    ]
