# Generated by Django 4.0 on 2023-02-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_options_account_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default=1, max_length=50, verbose_name='city'),
            preserve_default=False,
        ),
    ]
