# Generated by Django 4.0 on 2023-01-24 17:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_password_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='background_picture',
            field=models.ImageField(blank=True, null=True, upload_to='background-picture/'),
        ),
        migrations.AddField(
            model_name='account',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='headline'),
        ),
        migrations.AddField(
            model_name='account',
            name='show_headline_in_bio',
            field=models.BooleanField(default=False, verbose_name='I want to use this as my bio'),
        ),
        migrations.AddField(
            model_name='account',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Your Profile Summary'),
        ),
    ]
