# Generated by Django 4.0 on 2023-01-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_city_account_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_of_admission',
            field=models.DateField(auto_now=True, verbose_name='date of admission'),
        ),
        migrations.AddField(
            model_name='account',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True, verbose_name='registration number'),
        ),
    ]
