# Generated by Django 4.0 on 2023-01-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_date_of_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_admission',
            field=models.DateField(verbose_name='date of admission'),
        ),
    ]
