# Generated by Django 4.0 on 2023-01-18 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_password_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password_updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='password updated date'),
        ),
    ]
