# Generated by Django 4.0 on 2023-01-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_date_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_admission',
            field=models.DateField(null=True, verbose_name='date of admission'),
        ),
    ]
