# Generated by Django 4.0 on 2023-01-25 07:46

import config.helpers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['first_name', 'last_name', 'username'], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AddField(
            model_name='account',
            name='adress',
            field=models.CharField(max_length=50, null=True, verbose_name='adress'),
        ),
        migrations.AddField(
            model_name='account',
            name='father_name',
            field=models.CharField(help_text='Name contains only a-z and A-Z characters', max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Name contains only a-z and A-Z characters', regex="[a-zA-Z\\s']+")], verbose_name="father's name"),
        ),
        migrations.AddField(
            model_name='account',
            name='website_links',
            field=models.URLField(default='', verbose_name='website links'),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(null=True, upload_to=config.helpers.get_profile_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='account',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='registration number'),
        ),
    ]
