# Generated by Django 4.0 on 2023-01-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_account_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='registration number'),
        ),
    ]
