# Generated by Django 4.0 on 2023-01-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_alter_account_options_account_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=50)),
                ('url', models.URLField(default='')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_social_media', to='account.account')),
            ],
        ),
    ]
