# Generated by Django 4.0 on 2023-02-04 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('school', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='batches', to='school.Batch'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.account'),
        ),
        migrations.AddField(
            model_name='department',
            name='current_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.batch'),
        ),
    ]
