# Generated by Django 4.0 on 2023-01-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
