# Generated by Django 4.0 on 2023-02-08 15:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('departments', django.db.models.manager.Manager()),
            ],
        ),
    ]
