# Generated by Django 4.0 on 2023-02-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_remove_teacher_teacher'),
        ('school', '0004_remove_semester_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(related_name='lessons_teacher', to='teacher.Teacher'),
        ),
    ]
