# Generated by Django 4.0 on 2023-02-08 14:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_lesson_teachers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='awards',
            managers=[
                ('all_awards', django.db.models.manager.Manager()),
            ],
        ),
    ]
