# Generated by Django 4.0 on 2023-02-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_awards_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='awards',
            managers=[
            ],
        ),
    ]
