# Generated by Django 4.0 on 2023-02-08 15:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_awards_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='awards',
            managers=[
                ('awards', django.db.models.manager.Manager()),
            ],
        ),
    ]
