# Generated by Django 3.2 on 2023-02-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_awards_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teachers',
        ),
    ]
