# Generated by Django 4.0 on 2023-02-05 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.admissionstudent'),
            preserve_default=False,
        ),
    ]
