# Generated by Django 4.0 on 2023-02-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_admission_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionstudent',
            options={'verbose_name': 'Admission Student', 'verbose_name_plural': 'Admission Students'},
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='board',
            field=models.CharField(choices=[('CBSE', 'Central Board of Secondary Education'), ('ICSE', 'Indian Certificate of Secondary Education'), ('CISCE', 'Council for the Indian School Certificate Examination'), ('NIOS', 'National Institute of Open Schooling'), ('IB', 'International Baccalauring')], max_length=100, verbose_name='board'),
        ),
    ]
