# Generated by Django 4.0 on 2023-02-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('boy', 'Boy'), ('girl', 'Girl')], max_length=6, null=True, verbose_name='gender'),
        ),
    ]
