# Generated by Django 3.2 on 2023-02-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='is paying'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='is_scholarship',
            field=models.BooleanField(default=False, verbose_name='is scholarship'),
        ),
    ]
