# Generated by Django 3.2 on 2023-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20230215_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionstudent',
            name='paid',
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='board',
            field=models.CharField(choices=[('CBSE', 'Central Board of Secondary Education'), ('ICSE', 'Azerbaijian Certificate of Secondary Education'), ('CISCE', 'Council for the Azerbaijan School Certificate Examination'), ('NIOS', 'National Institute of Open Schooling'), ('IB', 'International Baccalauring')], max_length=100, verbose_name='board'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='is paid'),
        ),
    ]
