# Generated by Django 3.2 on 2023-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20230218_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='full_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
